quarkus:
  # Server port
  http:
    port: 8080

  # Logging
  log:
    level: INFO
    category:
      "org": INFO
      "com.intellias.basicsandbox.controller": INFO

  # Datasource
  datasource:
#    db-kind: postgresql
    username: user
    password: password
    jdbc:
      url: jdbc:postgresql://localhost:5433/sandbox_db

  # Hibernate ORM with Panache settings
  hibernate-orm:
    database:
      generation: validate
    log:
      sql: false
    dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway
  flyway:
    migrate-at-start: true
    locations: 'classpath:/db/migration/'

  # Quarkus security
  security:
    users:
      embedded:
        enabled: true
        plain-text: true
        users:
          user: password
        roles:
          user: USER

  # For health endpoint in Quarkus
  smallrye-health:
    root-path: /health
    liveness-path: /live
    readiness-path: /ready

  # Swagger-UI for Quarkus (If using OpenAPI)
  swagger-ui:
    always-include: true

# Custom app settings
app:
  dev:
    service-logging-enable: true

# Application Info
info:
  application:
    name: Java Sandbox Application
    description: Basic service to start your own by copying and adjusting for your needs
    version: '@project.version@'  # Please replace with actual versioning mechanism in Quarkus
